# Generated by Django 5.0.2 on 2024-03-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_vacc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child_data',
            name='contact_no',
        ),
        migrations.AddField(
            model_name='doctor_user',
            name='email',
            field=models.EmailField(default='abcd@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='parent_user',
            name='contact_no',
            field=models.IntegerField(default=1234567890),
        ),
    ]
