# Generated by Django 5.0.2 on 2024-03-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_vacc', '0002_remove_child_data_contact_no_doctor_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent_user',
            name='contact_no',
            field=models.CharField(default='1234567890', max_length=10),
        ),
    ]
