# Generated by Django 5.0.2 on 2024-03-30 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_vacc', '0004_doctor_user_contact_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='administered',
            fields=[
                ('administered_id', models.IntegerField(primary_key=True, serialize=False)),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_vacc.appointment')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_vacc.doctor_user')),
            ],
        ),
    ]
