# Generated by Django 5.0.2 on 2024-03-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_vacc', '0005_administered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administered',
            name='administered_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
